"""added relationship and serialization

Revision ID: f42b9060967c
Revises: 1d29cb83cf20
Create Date: 2024-10-06 11:01:07.609323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42b9060967c'
down_revision = '1d29cb83cf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero_powers', sa.Column('hero_id', sa.Integer(), nullable=False))
    op.add_column('hero_powers', sa.Column('power_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hero_powers', 'powers', ['power_id'], ['id'])
    op.create_foreign_key(None, 'hero_powers', 'heroes', ['hero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero_powers', type_='foreignkey')
    op.drop_constraint(None, 'hero_powers', type_='foreignkey')
    op.drop_column('hero_powers', 'power_id')
    op.drop_column('hero_powers', 'hero_id')
    # ### end Alembic commands ###
